// 노래방 인기곡 최고음 데이터베이스 (약 150곡)
// maxMidi: 곡 최고음 MIDI 번호 (C4 = 60). 커뮤니티 수집 데이터로 ±1키(반음) 오차가 있을 수 있음.
// falsetto: 최고음 구간이 원곡에서 가성으로 처리되는 곡이면 true
// gender: 'M' 남성곡, 'F' 여성곡, 'G' 그룹/혼성
window.SONG_DB = [
  // ── 남성 발라드 (클래식) ──
  { title: "옛사랑", artist: "이문세", gender: "M", tag: "발라드", maxMidi: 62, falsetto: false },
  { title: "광화문 연가", artist: "이문세", gender: "M", tag: "발라드", maxMidi: 62, falsetto: false },
  { title: "소녀", artist: "이문세", gender: "M", tag: "발라드", maxMidi: 63, falsetto: false },
  { title: "붉은 노을", artist: "이문세", gender: "M", tag: "발라드", maxMidi: 67, falsetto: false },
  { title: "서른 즈음에", artist: "김광석", gender: "M", tag: "발라드", maxMidi: 65, falsetto: false },
  { title: "이등병의 편지", artist: "김광석", gender: "M", tag: "발라드", maxMidi: 62, falsetto: false },
  { title: "먼지가 되어", artist: "김광석", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "사랑했지만", artist: "김광석", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "사랑하기 때문에", artist: "유재하", gender: "M", tag: "발라드", maxMidi: 66, falsetto: false },
  { title: "홀로 된다는 것", artist: "변진섭", gender: "M", tag: "발라드", maxMidi: 65, falsetto: false },
  { title: "너의 결혼식", artist: "015B", gender: "M", tag: "발라드", maxMidi: 66, falsetto: false },
  { title: "미소 속에 비친 그대", artist: "신승훈", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "I Believe", artist: "신승훈", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "투헤븐 (To Heaven)", artist: "조성모", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "아시나요", artist: "조성모", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "잘못된 만남", artist: "김건모", gender: "M", tag: "댄스", maxMidi: 68, falsetto: false },
  { title: "미안해요", artist: "김건모", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },

  // ── 남성 발라드 (2000s~) ──
  { title: "취중진담", artist: "전람회(김동률)", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "감사", artist: "김동률", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "다시 사랑한다 말할까", artist: "김동률", gender: "M", tag: "발라드", maxMidi: 67, falsetto: false },
  { title: "거리에서", artist: "성시경", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "내게 오는 길", artist: "성시경", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "희재", artist: "성시경", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "두 사람", artist: "성시경", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "너의 모든 순간", artist: "성시경", gender: "M", tag: "발라드", maxMidi: 67, falsetto: false },
  { title: "좋은 사람", artist: "토이(김연우)", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "사랑한다는 흔한 말", artist: "김연우", gender: "M", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "이별택시", artist: "김연우", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "눈의 꽃", artist: "박효신", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "야생화", artist: "박효신", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "좋은 사람", artist: "박효신", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "해줄 수 없는 일", artist: "박효신", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "Home", artist: "박효신", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "보고싶다", artist: "김범수", gender: "M", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "끝사랑", artist: "김범수", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "지나간다", artist: "김범수", gender: "M", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "바람기억", artist: "나얼", gender: "M", tag: "R&B", maxMidi: 74, falsetto: false },
  { title: "같은 시간 속의 너", artist: "나얼", gender: "M", tag: "R&B", maxMidi: 72, falsetto: false },
  { title: "너를 위해", artist: "임재범", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "고해", artist: "임재범", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "사랑보다 깊은 상처", artist: "임재범, 박정현", gender: "G", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "인연", artist: "이승철", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "서쪽하늘", artist: "이승철", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "그런 사람 또 없습니다", artist: "이승철", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "소주 한 잔", artist: "임창정", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "내가 저지른 사랑", artist: "임창정", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "술이 문제야", artist: "임창정", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "어디에도", artist: "엠씨더맥스", gender: "M", tag: "발라드", maxMidi: 75, falsetto: false },
  { title: "사랑의 시", artist: "엠씨더맥스", gender: "M", tag: "발라드", maxMidi: 74, falsetto: false },
  { title: "그대라는 사치", artist: "한동근", gender: "M", tag: "발라드", maxMidi: 74, falsetto: false },
  { title: "이 소설의 끝을 다시 써보려 해", artist: "한동근", gender: "M", tag: "발라드", maxMidi: 75, falsetto: false },
  { title: "가수가 된 이유", artist: "신용재", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "첫사랑", artist: "신용재", gender: "M", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "가을 안부", artist: "먼데이키즈", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "눈사람", artist: "정승환", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "이 바보야", artist: "정승환", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "안되나요", artist: "휘성", gender: "M", tag: "R&B", maxMidi: 71, falsetto: false },
  { title: "결혼까지 생각했어", artist: "휘성", gender: "M", tag: "R&B", maxMidi: 70, falsetto: false },
  { title: "가슴아파도", artist: "환희", gender: "M", tag: "R&B", maxMidi: 73, falsetto: false },
  { title: "벌써 일년", artist: "브라운아이즈", gender: "M", tag: "R&B", maxMidi: 70, falsetto: false },
  { title: "점점", artist: "브라운아이즈", gender: "M", tag: "R&B", maxMidi: 71, falsetto: false },
  { title: "Nothing Better", artist: "브라운아이드소울", gender: "M", tag: "R&B", maxMidi: 72, falsetto: false },
  { title: "정말 사랑했을까", artist: "브라운아이드소울", gender: "M", tag: "R&B", maxMidi: 71, falsetto: false },
  { title: "내사람", artist: "SG워너비", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "Timeless", artist: "SG워너비", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "라라라", artist: "SG워너비", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "이러지마 제발", artist: "케이윌", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "그 남자 그 여자", artist: "바이브", gender: "G", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "술이야", artist: "바이브", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "늦은 밤 너의 집 앞 골목길에서", artist: "노을", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "함께", artist: "노을", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "살다가", artist: "포맨", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "못해", artist: "포맨", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "한 남자", artist: "김종국", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "제자리 걸음", artist: "김종국", gender: "M", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "하늘을 달리다", artist: "이적", gender: "M", tag: "락", maxMidi: 71, falsetto: false },
  { title: "다행이다", artist: "이적", gender: "M", tag: "발라드", maxMidi: 67, falsetto: false },
  { title: "걱정말아요 그대", artist: "이적", gender: "M", tag: "발라드", maxMidi: 67, falsetto: false },
  { title: "헤어지자 말해요", artist: "박재정", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "고백", artist: "양다일", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "이별하러 가는 길", artist: "임한별", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "오늘도 빛나는 너에게", artist: "마크툽", gender: "M", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "Marry Me", artist: "마크툽", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "사월이 지나면 우리 헤어져요", artist: "첸", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "광화문에서", artist: "규현", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "그녀를 사랑해줘요", artist: "하동균", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "가족사진", artist: "김진호", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "모든 날, 모든 순간", artist: "폴킴", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "너를 만나", artist: "폴킴", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "비", artist: "폴킴", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "선물", artist: "멜로망스", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "사랑인가 봐", artist: "멜로망스", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "좋니", artist: "윤종신", gender: "M", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "오르막길", artist: "윤종신, 정인", gender: "G", tag: "발라드", maxMidi: 69, falsetto: false },
  { title: "신호등", artist: "이무진", gender: "M", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "취기를 빌려", artist: "산들", gender: "M", tag: "발라드", maxMidi: 68, falsetto: false },
  { title: "별 보러 가자", artist: "적재", gender: "M", tag: "어쿠스틱", maxMidi: 68, falsetto: false },
  { title: "봄봄봄", artist: "로이킴", gender: "M", tag: "어쿠스틱", maxMidi: 68, falsetto: false },
  { title: "그때 헤어지면 돼", artist: "로이킴", gender: "M", tag: "발라드", maxMidi: 69, falsetto: false },

  // ── 남성 락/밴드 ──
  { title: "가시", artist: "버즈", gender: "M", tag: "락", maxMidi: 71, falsetto: false },
  { title: "겁쟁이", artist: "버즈", gender: "M", tag: "락", maxMidi: 70, falsetto: false },
  { title: "천년의 사랑", artist: "박완규", gender: "M", tag: "락", maxMidi: 75, falsetto: false },
  { title: "금지된 사랑", artist: "김경호", gender: "M", tag: "락", maxMidi: 74, falsetto: false },
  { title: "사랑했지만", artist: "김경호", gender: "M", tag: "락", maxMidi: 73, falsetto: false },
  { title: "Don't Cry", artist: "더크로스", gender: "M", tag: "락", maxMidi: 75, falsetto: false },
  { title: "Never Ending Story", artist: "부활", gender: "M", tag: "락", maxMidi: 70, falsetto: false },
  { title: "사랑할수록", artist: "부활", gender: "M", tag: "락", maxMidi: 71, falsetto: false },
  { title: "비와 당신의 이야기", artist: "부활", gender: "M", tag: "락", maxMidi: 72, falsetto: false },
  { title: "사랑했나봐", artist: "윤도현", gender: "M", tag: "락", maxMidi: 71, falsetto: false },
  { title: "나는 나비", artist: "YB", gender: "M", tag: "락", maxMidi: 70, falsetto: false },
  { title: "흰수염고래", artist: "YB", gender: "M", tag: "락", maxMidi: 71, falsetto: false },
  { title: "아름다운 구속", artist: "김종서", gender: "M", tag: "락", maxMidi: 72, falsetto: false },
  { title: "Lazenca, Save Us", artist: "넥스트", gender: "M", tag: "락", maxMidi: 76, falsetto: false },
  { title: "돌덩이", artist: "하현우", gender: "M", tag: "락", maxMidi: 73, falsetto: false },
  { title: "주저하는 연인들을 위해", artist: "잔나비", gender: "M", tag: "밴드", maxMidi: 68, falsetto: true },
  { title: "뜨거운 여름밤은 가고 남은 건 볼품없지만", artist: "잔나비", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "TOMBOY", artist: "혁오", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "소녀 (오혁 ver.)", artist: "오혁", gender: "M", tag: "OST", maxMidi: 68, falsetto: true },
  { title: "위잉위잉", artist: "혁오", gender: "M", tag: "밴드", maxMidi: 68, falsetto: false },
  { title: "한 페이지가 될 수 있게", artist: "DAY6", gender: "M", tag: "밴드", maxMidi: 70, falsetto: false },
  { title: "예뻤어", artist: "DAY6", gender: "M", tag: "밴드", maxMidi: 71, falsetto: false },
  { title: "좋은 밤 좋은 꿈", artist: "너드커넥션", gender: "M", tag: "밴드", maxMidi: 68, falsetto: false },
  { title: "명동콜링", artist: "카더가든", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "봄이 좋냐??", artist: "10CM", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "폰서트", artist: "10CM", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야", artist: "장범준", gender: "M", tag: "밴드", maxMidi: 66, falsetto: false },
  { title: "잠이 오질 않네요", artist: "장범준", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "노래방에서", artist: "장범준", gender: "M", tag: "밴드", maxMidi: 71, falsetto: false },
  { title: "사랑이란 말이 어울리는 사람", artist: "장범준", gender: "M", tag: "밴드", maxMidi: 68, falsetto: false },
  { title: "하루종일", artist: "기리보이", gender: "M", tag: "힙합", maxMidi: 66, falsetto: false },
  { title: "좋아해", artist: "죠지", gender: "M", tag: "R&B", maxMidi: 68, falsetto: false },
  { title: "바라봐줘요", artist: "죠지", gender: "M", tag: "R&B", maxMidi: 67, falsetto: false },
  { title: "혼자두지마", artist: "백예린", gender: "F", tag: "R&B", maxMidi: 68, falsetto: false },
  { title: "짝사랑", artist: "10CM", gender: "M", tag: "밴드", maxMidi: 69, falsetto: false },
  { title: "사랑으로", artist: "wave to earth", gender: "M", tag: "밴드", maxMidi: 66, falsetto: false },
  { title: "사랑이 아니라 말하지 말아요", artist: "김동률", gender: "M", tag: "발라드", maxMidi: 66, falsetto: false },
  { title: "벚꽃 엔딩", artist: "버스커 버스커", gender: "M", tag: "밴드", maxMidi: 66, falsetto: false },

  // ── 남성 R&B/힙합/팝 ──
  { title: "instagram", artist: "DEAN", gender: "M", tag: "R&B", maxMidi: 69, falsetto: true },
  { title: "D (half moon)", artist: "DEAN", gender: "M", tag: "R&B", maxMidi: 68, falsetto: true },
  { title: "양화대교", artist: "자이언티", gender: "M", tag: "R&B", maxMidi: 68, falsetto: true },
  { title: "꺼내 먹어요", artist: "자이언티", gender: "M", tag: "R&B", maxMidi: 66, falsetto: false },
  { title: "Beautiful", artist: "크러쉬", gender: "M", tag: "R&B", maxMidi: 70, falsetto: false },
  { title: "아무노래", artist: "지코", gender: "M", tag: "힙합", maxMidi: 64, falsetto: false },
  { title: "사랑을 했다", artist: "iKON", gender: "G", tag: "팝", maxMidi: 65, falsetto: false },
  { title: "봄날", artist: "방탄소년단", gender: "G", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "거짓말", artist: "god", gender: "G", tag: "팝", maxMidi: 68, falsetto: false },
  { title: "길", artist: "god", gender: "G", tag: "팝", maxMidi: 67, falsetto: false },
  { title: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", artist: "AKMU", gender: "G", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "오랜 날 오랜 밤", artist: "AKMU", gender: "G", tag: "팝", maxMidi: 68, falsetto: false },

  // ── 트로트 ──
  { title: "안동역에서", artist: "진성", gender: "M", tag: "트로트", maxMidi: 67, falsetto: false },
  { title: "테스형!", artist: "나훈아", gender: "M", tag: "트로트", maxMidi: 68, falsetto: false },
  { title: "아모르파티", artist: "김연자", gender: "F", tag: "트로트", maxMidi: 69, falsetto: false },
  { title: "어머나", artist: "장윤정", gender: "F", tag: "트로트", maxMidi: 66, falsetto: false },
  { title: "찐이야", artist: "영탁", gender: "M", tag: "트로트", maxMidi: 68, falsetto: false },
  { title: "사랑은 늘 도망가", artist: "임영웅", gender: "M", tag: "트로트", maxMidi: 68, falsetto: false },
  { title: "이제 나만 믿어요", artist: "임영웅", gender: "M", tag: "트로트", maxMidi: 68, falsetto: false },

  // ── 여성 발라드 ──
  { title: "인연", artist: "이선희", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "만약에", artist: "태연", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "사계 (Four Seasons)", artist: "태연", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "I", artist: "태연", gender: "F", tag: "팝", maxMidi: 72, falsetto: false },
  { title: "기억상실", artist: "거미", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "친구라도 될 걸 그랬어", artist: "거미", gender: "F", tag: "R&B", maxMidi: 71, falsetto: false },
  { title: "You Are My Everything", artist: "거미", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "첫눈처럼 너에게 가겠다", artist: "에일리", gender: "F", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "보여줄게", artist: "에일리", gender: "F", tag: "팝", maxMidi: 72, falsetto: false },
  { title: "노래가 늘었어", artist: "에일리", gender: "F", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "시간을 거슬러", artist: "린", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "사랑했잖아", artist: "린", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "총 맞은 것처럼", artist: "백지영", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "사랑 안 해", artist: "백지영", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "잊지 말아요", artist: "백지영", gender: "F", tag: "발라드", maxMidi: 70, falsetto: false },
  { title: "체념", artist: "빅마마", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "안녕이라고 말하지마", artist: "다비치", gender: "F", tag: "발라드", maxMidi: 73, falsetto: false },
  { title: "8282", artist: "다비치", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "거북이", artist: "다비치", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "꿈에", artist: "박정현", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "한숨", artist: "이하이", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "그때가 좋았어", artist: "케이시", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "열애중", artist: "벤", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "180도", artist: "벤", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "하늘바라기", artist: "정은지", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "여인의 향기", artist: "씨야", gender: "F", tag: "발라드", maxMidi: 72, falsetto: false },
  { title: "나의 X에게", artist: "경서", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "밤하늘의 별을", artist: "경서", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "다정히 내 이름을 부르면", artist: "경서예지, 전건호", gender: "G", tag: "발라드", maxMidi: 72, falsetto: false },

  // ── 여성 팝/락 ──
  { title: "Tears", artist: "소찬휘", gender: "F", tag: "락", maxMidi: 75, falsetto: false },
  { title: "밤편지", artist: "아이유", gender: "F", tag: "발라드", maxMidi: 65, falsetto: false },
  { title: "좋은 날", artist: "아이유", gender: "F", tag: "팝", maxMidi: 78, falsetto: false },
  { title: "Love poem", artist: "아이유", gender: "F", tag: "발라드", maxMidi: 71, falsetto: false },
  { title: "에잇", artist: "아이유", gender: "F", tag: "팝", maxMidi: 69, falsetto: false },
  { title: "팔레트", artist: "아이유", gender: "F", tag: "팝", maxMidi: 68, falsetto: false },
  { title: "라일락", artist: "아이유", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "블루밍", artist: "아이유", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "Celebrity", artist: "아이유", gender: "F", tag: "팝", maxMidi: 70, falsetto: true },
  { title: "사건의 지평선", artist: "윤하", gender: "F", tag: "락발라드", maxMidi: 71, falsetto: false },
  { title: "오르트구름", artist: "윤하", gender: "F", tag: "락발라드", maxMidi: 72, falsetto: false },
  { title: "기다리다", artist: "윤하", gender: "F", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "비도 오고 그래서", artist: "헤이즈", gender: "F", tag: "R&B", maxMidi: 69, falsetto: false },
  { title: "저 별", artist: "헤이즈", gender: "F", tag: "R&B", maxMidi: 70, falsetto: false },
  { title: "우주를 줄게", artist: "볼빨간사춘기", gender: "F", tag: "팝", maxMidi: 69, falsetto: false },
  { title: "여행", artist: "볼빨간사춘기", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "썸 탈꺼야", artist: "볼빨간사춘기", gender: "F", tag: "팝", maxMidi: 69, falsetto: false },
  { title: "별이 빛나는 밤", artist: "마마무", gender: "F", tag: "팝", maxMidi: 72, falsetto: false },
  { title: "데칼코마니", artist: "마마무", gender: "F", tag: "팝", maxMidi: 72, falsetto: false },
  { title: "마리아 (Maria)", artist: "화사", gender: "F", tag: "팝", maxMidi: 70, falsetto: false },
  { title: "그건 아마 우리의 잘못은 아닐 거야", artist: "백예린", gender: "F", tag: "팝", maxMidi: 69, falsetto: false },
  { title: "롤린 (Rollin')", artist: "브레이브걸스", gender: "F", tag: "댄스", maxMidi: 70, falsetto: false },
  { title: "다시 만난 세계", artist: "소녀시대", gender: "F", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "Gee", artist: "소녀시대", gender: "F", tag: "댄스", maxMidi: 68, falsetto: false },
  { title: "Tell Me", artist: "원더걸스", gender: "F", tag: "댄스", maxMidi: 66, falsetto: false },
  { title: "Nobody", artist: "원더걸스", gender: "F", tag: "댄스", maxMidi: 68, falsetto: false },
  { title: "너 때문에 미쳐", artist: "티아라", gender: "F", tag: "댄스", maxMidi: 69, falsetto: false },
  { title: "시간을 달려서", artist: "여자친구", gender: "F", tag: "팝", maxMidi: 71, falsetto: false },
  { title: "해야 (HEYA)", artist: "아이브", gender: "F", tag: "댄스", maxMidi: 73, falsetto: false },
  { title: "LOVE DIVE", artist: "아이브", gender: "F", tag: "댄스", maxMidi: 69, falsetto: false },
  { title: "ANTIFRAGILE", artist: "르세라핌", gender: "F", tag: "댄스", maxMidi: 69, falsetto: false },
  { title: "Ditto", artist: "NewJeans", gender: "F", tag: "팝", maxMidi: 67, falsetto: false },
  { title: "Hype Boy", artist: "NewJeans", gender: "F", tag: "팝", maxMidi: 68, falsetto: false },
  { title: "Next Level", artist: "aespa", gender: "F", tag: "댄스", maxMidi: 69, falsetto: false },
];
